### ISSUE TITLE
Bitrates events are always undefined

### ISSUE THREAD

**Issue by gbayomi** [BGS-Libraries/Cast-Player-Sample#2]
Even using the API example, the quality level of the video still appears undefined.

It is definitely possible to make it work, but it's better to use another sender application, since this is inherently related with the sender-receiver relationship.

**Comment by firekesti** [comment]
This might be an issue with the manifest of the stream too - not sure.

**Comment by gbayomi** [comment]
Ok! I will look that up and try to make it work as soon as possible.

**Comment by gbayomi** [comment]
Fixed! I don't know exactly why it worked, but it is working now haha. I believe one of the methods were not called correctly to acquire the bitrate.

**Comment by gbayomi** [comment]
The bitrates and also the captions. I don't know exactly how to integrate the captions, but the data storage is working
